local core = require("scripts.core")

local function box() return core.new_box() end
local function key(name, q, lane) return name .. "\0" .. q .. "\0" .. lane end
local function accept(b, name, q, lane, n, size, tick, pass)
  return core.accept(b, name, q, lane, n, size, tick or 1, pass or false)
end

describe("core", function()
  it("new box is idle and green", function()
    local b = box(); eq(core.is_idle(b), true); eq(core.led_state(b), "green")
  end)
  it("same item on two lanes keeps two buffers", function()
    local b = box(); accept(b,"iron","normal",1,10,50); accept(b,"iron","normal",2,10,50); eq(core.used_slots(b),2)
  end)
  it("quality is separate buffer", function()
    local b = box(); accept(b,"iron","normal",1,1,50); accept(b,"iron","rare",1,1,50); eq(core.used_slots(b),2)
  end)
  it("full stack becomes ready on its lane", function()
    local b = box(); eq(accept(b,"iron","normal",1,50,50),50); eq(core.peek_out(b,1),{name="iron",quality="normal",count=50,passthrough=false}); eq(core.peek_out(b,2),nil)
  end)
  it("ready stacks leave in ready order", function()
    local b=box(); accept(b,"iron","normal",1,50,50,1); accept(b,"copper","normal",1,50,50,2); eq(core.peek_out(b,1).name,"iron"); core.take_out(b,1,50); eq(core.peek_out(b,1).name,"copper")
  end)
  it("arrival after ready starts new partial", function()
    local b=box(); accept(b,"iron","normal",1,50,50,1); accept(b,"iron","normal",1,3,50,2); eq(core.used_slots(b),2); eq(core.peek_out(b,1).count,50); eq(core.totals(b),{{name="iron",quality="normal",count=53}})
  end)
  it("accept splits across ready and new partial", function()
    local b=box(); eq(accept(b,"iron","normal",1,60,50),60); eq(core.used_slots(b),2); eq(core.peek_out(b,1).count,50); eq(core.totals(b),{{name="iron",quality="normal",count=60}})
  end)
  it("used slots counts ready and partials", function()
    local b=box(); accept(b,"iron","normal",1,50,50); accept(b,"copper","normal",2,2,50); eq(core.used_slots(b),2); eq(core.free_slots(b),46)
  end)
  it("full box flushes oldest partial and accepts zero", function()
    local b=box(); for i=1,48 do accept(b,"i"..i,"normal",1,1,50,i) end; eq(core.used_slots(b),48); eq(accept(b,"extra","normal",2,1,50,99),0); eq(core.peek_out(b,1).name,"i1"); eq(core.used_slots(b),48)
  end)
  it("oldest partial chosen across lanes", function()
    -- oldest partial sits on lane 2; new item arrives on lane 1
    local b=box(); accept(b,"old2","normal",2,1,50,1); for i=2,48 do accept(b,"i"..i,"normal",1,1,50,i) end
    eq(accept(b,"extra","normal",1,1,50,99),0); eq(core.peek_out(b,2).name,"old2"); eq(core.peek_out(b,1),nil)
  end)
  it("all ready refuses input", function()
    local b=box(); for i=1,48 do accept(b,"i"..i,"normal",1,50,50,i) end; eq(accept(b,"extra","normal",2,1,50,99),0); eq(core.used_slots(b),48)
  end)
  it("passthrough uses hold not slots", function()
    local b=box(); eq(accept(b,"iron","normal",1,4,4,1,true),4); eq(core.used_slots(b),0); eq(core.peek_out(b,1),{name="iron",quality="normal",count=4,passthrough=true})
  end)
  it("hold busy refuses second passthrough", function()
    local b=box(); accept(b,"iron","normal",1,4,4,1,true); eq(accept(b,"copper","normal",1,1,1,2,true),0); eq(core.hold_items(b),{{name="iron",quality="normal",count=4}})
  end)
  it("hold waits while stack run started", function()
    local b=box(); accept(b,"iron","normal",1,50,50); core.take_out(b,1,1); accept(b,"copper","normal",1,2,2,2,true); eq(core.peek_out(b,1),{name="iron",quality="normal",count=49,passthrough=false})
  end)
  it("hold goes before unstarted stack", function()
    local b=box(); accept(b,"iron","normal",1,50,50); accept(b,"copper","normal",1,2,2,2,true); eq(core.peek_out(b,1),{name="copper",quality="normal",count=2,passthrough=true})
  end)
  it("take out last piece may be small", function()
    local b=box(); accept(b,"ore","normal",1,50,50); for i=1,12 do eq(core.peek_out(b,1).count,50-(i-1)*4); core.take_out(b,1,4) end; eq(core.peek_out(b,1).count,2); core.take_out(b,1,2); eq(core.peek_out(b,1),nil); eq(core.used_slots(b),0)
  end)
  it("timeout flushes old partial only", function()
    local b=box(); accept(b,"old","normal",1,2,50,1); accept(b,"new","normal",2,3,50,8); core.on_tick(b,6,5); eq(core.peek_out(b,1).name,"old"); eq(core.peek_out(b,2),nil)
  end)
  it("timeout zero is off", function()
    local b=box(); accept(b,"old","normal",1,2,50,1); core.on_tick(b,100,0); eq(core.peek_out(b,1),nil); eq(core.used_slots(b),1)
  end)
  it("flush partials queues all in arrival order", function()
    -- same lane, arrival order differs from insertion order
    local b=box(); accept(b,"c","normal",1,1,50,7); accept(b,"a","normal",1,1,50,2); accept(b,"b","normal",1,1,50,4); core.flush_partials(b,8)
    local seen={}; for i=1,3 do local o=core.peek_out(b,1); seen[i]=o.name; core.take_out(b,1,1) end; eq(seen,{"a","b","c"})
  end)
  it("remove external takes newest partial first", function()
    -- lane 1 partial older (tick 1, 3 items), lane 2 newer (tick 2, 5 items); remove 4 -> lane 2 left 1, lane 1 keeps 3
    local b=box(); accept(b,"iron","normal",1,3,50,1); accept(b,"iron","normal",2,5,50,2); eq(core.remove_external(b,"iron","normal",4),4)
    core.flush_partials(b,3); eq(core.peek_out(b,1).count,3); eq(core.peek_out(b,2).count,1)
    -- then ready stacks, latest readied first
    local c=box(); accept(c,"ore","normal",1,50,50,1); accept(c,"ore","normal",2,50,50,2); eq(core.remove_external(c,"ore","normal",10),10)
    eq(core.peek_out(c,1).count,50); eq(core.peek_out(c,2).count,40)
  end)
  it("adopt external lands on lane one", function()
    local b=box(); eq(core.adopt_external(b,"iron","normal",55,50,1),55); eq(core.peek_out(b,1).count,50); eq(core.peek_out(b,2),nil); eq(core.used_slots(b),2)
  end)
  it("led yellow with items and red when full", function()
    local b=box(); accept(b,"iron","normal",1,1,50); eq(core.led_state(b),"yellow"); for i=2,48 do accept(b,"i"..i,"normal",1,1,50,i) end; eq(core.led_state(b),"red")
  end)
  it("totals sums lanes sorted", function()
    local b=box(); accept(b,"z","normal",2,2,50); accept(b,"a","rare",1,3,50); accept(b,"a","normal",2,4,50); accept(b,"a","normal",1,6,50)
    eq(core.totals(b),{{name="a",quality="normal",count=10},{name="a",quality="rare",count=3},{name="z",quality="normal",count=2}})
  end)
  it("box is plain data", function()
    local b=box(); accept(b,"iron","normal",1,2,50); accept(b,"copper","rare",2,1,50,3,true); local function walk(v) local t=type(v); ok(t=="table" or t=="number" or t=="string" or t=="boolean"); if t=="table" then for k,x in pairs(v) do walk(k); walk(x) end end end; walk(b)
  end)
  -- S1 v8 (D-5): per-lane slot and per-key item counters kept by core, rebuilt for old saves.
  it("counters track partial and ready per lane", function()
    local b = box()
    accept(b, "iron", "normal", 1, 3, 4, 1)           -- partial 3 on lane 1
    accept(b, "iron", "normal", 1, 2, 4, 2)           -- fills 4 -> ready, new partial 1
    accept(b, "coal", "normal", 2, 4, 4, 3)           -- ready on lane 2
    eq(b.lane_used, { 2, 1 })
    eq(b.held[key("iron", "normal", 1)], 5); eq(b.held[key("coal", "normal", 2)], 4)
    core.take_out(b, 1, 4)                            -- ready iron leaves
    eq(b.lane_used, { 1, 1 }); eq(b.held[key("iron", "normal", 1)], 1)
    core.remove_external(b, "iron", "normal", 1)      -- player took last iron
    eq(b.lane_used, { 0, 1 }); eq(b.held[key("iron", "normal", 1)], nil)
    core.take_out(b, 2, 4)
    eq(b.lane_used, { 0, 0 }); eq(b.held[key("coal", "normal", 2)], nil)
  end)
  it("counters rebuilt for old box", function()
    local b = box()
    accept(b, "iron", "normal", 1, 6, 4, 1)
    accept(b, "coal", "rare", 2, 1, 4, 1)
    b.lane_used, b.held = nil, nil                    -- v1.7 save: no counters
    accept(b, "coal", "rare", 2, 1, 4, 2)
    eq(b.lane_used, { 2, 1 })
    eq(b.held[key("iron", "normal", 1)], 6); eq(b.held[key("coal", "rare", 2)], 2)
  end)
  it("accept passes item stack to room stubs", function()
    local b = box()
    local seen
    local real = core.item_room
    core.item_room = function(bx, name, q, lane, item_stack) seen = { name, q, lane, item_stack }; return real(bx, name, q, lane, item_stack) end
    core.accept(b, "iron", "normal", 2, 1, 4, 1, false, 100)
    core.item_room = real
    eq(seen, { "iron", "normal", 2, 100 })
  end)
end)
