local circuit = require("scripts.circuit")

describe("circuit", function()
  it("compare all six comparators", function()
    eq(circuit.compare(3, ">", 2), true)
    eq(circuit.compare(2, "<", 3), true)
    eq(circuit.compare(3, "=", 3), true)
    eq(circuit.compare(3, "≥", 3), true)
    eq(circuit.compare(3, "≤", 3), true)
    eq(circuit.compare(2, "≠", 3), true)
  end)

  it("compare unknown comparator is false", function()
    eq(circuit.compare(1, "??", 1), false)
  end)
end)
