#!/bin/sh
# Stage mod for one Factorio version into build/<FV>/: mods/sushi-packer_<ver>/, mod-list.json, config.ini.
# usage: tools/stage.sh <2.0|2.1> [test|release]
# test = include tests/ (in-game test files); release = shipped files only.
set -eu
FV=${1:?usage: tools/stage.sh <2.0|2.1> [test|release]}
MODE=${2:-test}
ROOT=$(cd "$(dirname "$0")/.." && pwd)
case "$FV" in
  2.0) VER=0.1.13 ;;
  2.1) VER=0.2.13 ;;
  *) echo "stage: FV must be 2.0 or 2.1" >&2; exit 2 ;;
esac
OUT=${STAGE_DIR:-$ROOT/build/$FV}
FACTORIO=${FACTORIO_ROOT:-$HOME/factorio-$FV/factorio}
# release zip needs no Factorio (GitHub Actions runner); test staging does (mod-list + config.ini).
if [ "$MODE" != release ]; then
  test -x "$FACTORIO/bin/x64/factorio" || { echo "stage: no Factorio at $FACTORIO (make factorio FV=$FV)" >&2; exit 2; }
fi
MOD="$OUT/mods/sushi-packer_$VER"
rm -rf "$OUT/mods/sushi-packer_"*
mkdir -p "$MOD" "$OUT/write"
for f in info.json data.lua data-final-fixes.lua settings.lua control.lua changelog.txt thumbnail.png LICENSE; do
  test -e "$ROOT/$f" && cp "$ROOT/$f" "$MOD/"
done
for d in scripts prototypes locale graphics; do cp -r "$ROOT/$d" "$MOD/"; done
rm -rf "$OUT/mods/sushi-packer-test-env_"* "$OUT/mods/sushi-packer-test-settings_"*
# v9 MODSET (env): third-party belt mods from ~/.cache/sushi-packer-mods/<FV> (tools/fetch_mods.py fetch first).
# Old third-party zips always removed; startup overrides go into generated test-only mod sushi-packer-test-settings.
python3 - "$ROOT" "$FV" "$OUT/mods" "${MODSET:-}" <<'PY'
import errno, json, os, shutil, subprocess, sys
root, fv, mods, modset = sys.argv[1:]
lock = json.load(open(os.path.join(root, "tests", "mods.lock.json")))
files = {e["file"] for v in lock.values() for e in v.values()}
os.makedirs(mods, exist_ok=True)
for f in os.listdir(mods):
    if f in files: os.remove(os.path.join(mods, f))
names = []
if modset:
    names = subprocess.check_output([os.path.join(root, "tools", "fetch_mods.py"), "list", fv, modset], text=True).split()
    for n in names:
        src = os.path.join(os.path.expanduser("~/.cache/sushi-packer-mods"), fv, lock[fv][n]["file"])
        if not os.path.exists(src): sys.exit(f"stage: {src} missing (tools/fetch_mods.py fetch {fv} {modset})")
        dst = os.path.join(mods, os.path.basename(src))  # hardlink: no extra bytes (disk floor, skills_disk_check 2026-09-28)
        try:
            os.link(src, dst)
        except OSError as e:
            if e.errno != errno.EXDEV: raise
            shutil.copy(src, dst)
    settings = json.load(open(os.path.join(root, "tools", "modsets.json")))[modset].get("settings", {})
    if settings:
        d = os.path.join(mods, "sushi-packer-test-settings_0.0.1"); os.makedirs(d)
        json.dump({"name": "sushi-packer-test-settings", "version": "0.0.1", "title": "Sushi Packer test startup settings (never shipped)",
                   "author": "dw3105", "factorio_version": fv, "dependencies": ["base"] + [n for n in names]}, open(os.path.join(d, "info.json"), "w"), indent=2)
        lines = ["-- generated by tools/stage.sh for MODSET=" + modset]
        for k, v in sorted(settings.items()):
            lua = "true" if v is True else "false" if v is False else json.dumps(v)
            lines.append('for _, t in ipairs({"bool-setting","int-setting","double-setting","string-setting"}) do local s = data.raw[t] and data.raw[t]["%s"]; if s then s.default_value = %s; if s.hidden then s.forced_value = %s end end end' % (k, lua, lua))
        open(os.path.join(d, "settings-final-fixes.lua"), "w").write("\n".join(lines) + "\n")
        names.append("sushi-packer-test-settings")
open(os.path.join(mods, ".modset"), "w").write("\n".join(names))
# v10: builtin_off set = no-SA game (space-age, quality, elevated-rails, recycler disabled in mod-list).
off = os.path.join(mods, ".builtin_off")
if os.path.exists(off): os.remove(off)
if modset and json.load(open(os.path.join(root, "tools", "modsets.json")))[modset].get("builtin_off"):
    open(off, "w").write("1")
PY
if [ "$MODE" = test ]; then
  mkdir -p "$MOD/tests"; cp -r "$ROOT/tests/game" "$MOD/tests/"
  # test-only helper mod: engine max belt stack 8 (proves research-set release beyond vanilla 4)
  ENV="$OUT/mods/sushi-packer-test-env_0.0.1"; cp -r "$ROOT/tests/env/sushi-packer-test-env" "$ENV"
  python3 -c "import json,sys; p=sys.argv[1]; d=json.load(open(p)); d['factorio_version']=sys.argv[2]; json.dump(d,open(p,'w'),indent=2)" "$ENV/info.json" "$FV"
fi
python3 - "$MOD/info.json" "$FV" "$VER" "$MODE" <<'PY'
import json, sys
p, fv, ver, mode = sys.argv[1:]
d = json.load(open(p)); d["factorio_version"] = fv; d["version"] = ver
if mode == "release":
    d["dependencies"] = [dep for dep in d.get("dependencies", []) if "factorio-test" not in dep]
json.dump(d, open(p, "w"), indent=2)
PY
if [ "$MODE" = release ] && [ ! -d "$FACTORIO/data" ]; then echo "$MOD"; exit 0; fi
# Enable every bundled data mod present in this build (2.1 adds recycler) plus ours and any extra zips in mods/.
python3 - "$FACTORIO/data" "$OUT/mods" <<'PY'
import json, os, sys
data, mods = sys.argv[1:]
bundled = [n for n in ("base", "elevated-rails", "quality", "recycler", "space-age") if os.path.isdir(os.path.join(data, n))]
off = [n for n in bundled if n != "base"] if os.path.exists(os.path.join(mods, ".builtin_off")) else []
names = [n for n in bundled if n not in off]
names += ["sushi-packer"]
for f in os.listdir(mods):
    if f.startswith("factorio-test_"): names.append("factorio-test")
    if f.startswith("sushi-packer-test-env_"): names.append("sushi-packer-test-env")
ms = os.path.join(mods, ".modset")
if os.path.exists(ms): names += open(ms).read().split()
json.dump({"mods": [{"name": n, "enabled": True} for n in dict.fromkeys(names)] + [{"name": n, "enabled": False} for n in off]},
          open(os.path.join(mods, "mod-list.json"), "w"), indent=2)
PY
cat > "$OUT/config.ini" <<CFG
[path]
read-data=$FACTORIO/data
write-data=$OUT/write
CFG
echo "$MOD"
